// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface GetAllReservationsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllReservationsRequest)
    com.google.protobuf.MessageOrBuilder {
}
