// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface GetAllClientsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllClientsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Client clients = 1;</code>
   */
  java.util.List<com.res.reservation.stubs.Client> 
      getClientsList();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  com.res.reservation.stubs.Client getClients(int index);
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  java.util.List<? extends com.res.reservation.stubs.ClientOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  com.res.reservation.stubs.ClientOrBuilder getClientsOrBuilder(
      int index);
}
