// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface SaveClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientRequest client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.ClientRequest client = 1;</code>
   * @return The client.
   */
  com.res.reservation.stubs.ClientRequest getClient();
  /**
   * <code>.ClientRequest client = 1;</code>
   */
  com.res.reservation.stubs.ClientRequestOrBuilder getClientOrBuilder();
}
