// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface ClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nom = 1;</code>
   * @return The nom.
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 1;</code>
   * @return The bytes for nom.
   */
  com.google.protobuf.ByteString
      getNomBytes();

  /**
   * <code>string prenom = 2;</code>
   * @return The prenom.
   */
  java.lang.String getPrenom();
  /**
   * <code>string prenom = 2;</code>
   * @return The bytes for prenom.
   */
  com.google.protobuf.ByteString
      getPrenomBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string telephone = 4;</code>
   * @return The telephone.
   */
  java.lang.String getTelephone();
  /**
   * <code>string telephone = 4;</code>
   * @return The bytes for telephone.
   */
  com.google.protobuf.ByteString
      getTelephoneBytes();
}
