// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface GetAllClientsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllClientsRequest)
    com.google.protobuf.MessageOrBuilder {
}
