// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface GetAllChambresRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllChambresRequest)
    com.google.protobuf.MessageOrBuilder {
}
