// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface GetClientByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetClientByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Client client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 1;</code>
   * @return The client.
   */
  com.res.reservation.stubs.Client getClient();
  /**
   * <code>.Client client = 1;</code>
   */
  com.res.reservation.stubs.ClientOrBuilder getClientOrBuilder();
}
