// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface ReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dateDebut = 1;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 1;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 2;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 2;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>string preferences = 3;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <code>string preferences = 3;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();

  /**
   * <code>string clientId = 4;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 4;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string chambreId = 5;</code>
   * @return The chambreId.
   */
  java.lang.String getChambreId();
  /**
   * <code>string chambreId = 5;</code>
   * @return The bytes for chambreId.
   */
  com.google.protobuf.ByteString
      getChambreIdBytes();
}
