// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public final class ReservationOuterClass {
  private ReservationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chambre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Chambre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllClientsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllClientsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllClientsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllClientsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClientByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClientByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetClientByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetClientByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChambreByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChambreByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChambreByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChambreByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllChambresRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllChambresRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllChambresResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllChambresResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Reservation.proto\"S\n\006Client\022\n\n\002id\030\001 \001(" +
      "\t\022\013\n\003nom\030\002 \001(\t\022\016\n\006prenom\030\003 \001(\t\022\r\n\005email\030" +
      "\004 \001(\t\022\021\n\ttelephone\030\005 \001(\t\"N\n\rClientReques" +
      "t\022\013\n\003nom\030\001 \001(\t\022\016\n\006prenom\030\002 \001(\t\022\r\n\005email\030" +
      "\003 \001(\t\022\021\n\ttelephone\030\004 \001(\t\"w\n\007Chambre\022\n\n\002i" +
      "d\030\001 \001(\t\022\032\n\004type\030\002 \001(\0162\014.TypeChambre\022\014\n\004p" +
      "rix\030\003 \001(\002\022\022\n\ndisponible\030\004 \001(\010\022\"\n\014reserva" +
      "tions\030\005 \003(\0132\014.Reservation\"N\n\016ChambreRequ" +
      "est\022\032\n\004type\030\001 \001(\0162\014.TypeChambre\022\014\n\004prix\030" +
      "\002 \001(\002\022\022\n\ndisponible\030\003 \001(\010\"\206\001\n\013Reservatio" +
      "n\022\n\n\002id\030\001 \001(\t\022\021\n\tdateDebut\030\002 \001(\t\022\017\n\007date" +
      "Fin\030\003 \001(\t\022\023\n\013preferences\030\004 \001(\t\022\027\n\006client" +
      "\030\005 \001(\0132\007.Client\022\031\n\007chambre\030\006 \001(\0132\010.Chamb" +
      "re\"r\n\022ReservationRequest\022\021\n\tdateDebut\030\001 " +
      "\001(\t\022\017\n\007dateFin\030\002 \001(\t\022\023\n\013preferences\030\003 \001(" +
      "\t\022\020\n\010clientId\030\004 \001(\t\022\021\n\tchambreId\030\005 \001(\t\"\026" +
      "\n\024GetAllClientsRequest\"1\n\025GetAllClientsR" +
      "esponse\022\030\n\007clients\030\001 \003(\0132\007.Client\"\"\n\024Get" +
      "ClientByIdRequest\022\n\n\002id\030\001 \001(\t\"0\n\025GetClie" +
      "ntByIdResponse\022\027\n\006client\030\001 \001(\0132\007.Client\"" +
      "3\n\021SaveClientRequest\022\036\n\006client\030\001 \001(\0132\016.C" +
      "lientRequest\"-\n\022SaveClientResponse\022\027\n\006cl" +
      "ient\030\001 \001(\0132\007.Client\"!\n\023DeleteClientReque" +
      "st\022\n\n\002id\030\001 \001(\t\"\'\n\024DeleteClientResponse\022\017" +
      "\n\007success\030\001 \001(\010\"#\n\025GetChambreByIdRequest" +
      "\022\n\n\002id\030\001 \001(\t\"3\n\026GetChambreByIdResponse\022\031" +
      "\n\007chambre\030\001 \001(\0132\010.Chambre\"6\n\022SaveChambre" +
      "Request\022 \n\007chambre\030\001 \001(\0132\017.ChambreReques" +
      "t\"0\n\023SaveChambreResponse\022\031\n\007chambre\030\001 \001(" +
      "\0132\010.Chambre\"\"\n\024DeleteChambreRequest\022\n\n\002i" +
      "d\030\001 \001(\t\"(\n\025DeleteChambreResponse\022\017\n\007succ" +
      "ess\030\001 \001(\010\"\'\n\031GetReservationByIdRequest\022\n" +
      "\n\002id\030\001 \001(\t\"?\n\032GetReservationByIdResponse" +
      "\022!\n\013reservation\030\001 \001(\0132\014.Reservation\"B\n\026S" +
      "aveReservationRequest\022(\n\013reservation\030\001 \001" +
      "(\0132\023.ReservationRequest\"<\n\027SaveReservati" +
      "onResponse\022!\n\013reservation\030\001 \001(\0132\014.Reserv" +
      "ation\"&\n\030DeleteReservationRequest\022\n\n\002id\030" +
      "\001 \001(\t\",\n\031DeleteReservationResponse\022\017\n\007su" +
      "ccess\030\001 \001(\010\"\033\n\031GetAllReservationsRequest" +
      "\"@\n\032GetAllReservationsResponse\022\"\n\014reserv" +
      "ations\030\001 \003(\0132\014.Reservation\"\027\n\025GetAllCham" +
      "bresRequest\"4\n\026GetAllChambresResponse\022\032\n" +
      "\010chambres\030\001 \003(\0132\010.Chambre*%\n\013TypeChambre" +
      "\022\n\n\006SIMPLE\020\000\022\n\n\006DOUBLE\020\0012\375\001\n\rClientServi" +
      "ce\022;\n\nAllClients\022\025.GetAllClientsRequest\032" +
      "\026.GetAllClientsResponse\022;\n\nClientById\022\025." +
      "GetClientByIdRequest\032\026.GetClientByIdResp" +
      "onse\0225\n\nSaveClient\022\022.SaveClientRequest\032\023" +
      ".SaveClientResponse\022;\n\014deleteClient\022\024.De" +
      "leteClientRequest\032\025.DeleteClientResponse" +
      "2\212\002\n\016ChambreService\022>\n\013AllChambres\022\026.Get" +
      "AllChambresRequest\032\027.GetAllChambresRespo" +
      "nse\022>\n\013ChambreById\022\026.GetChambreByIdReque" +
      "st\032\027.GetChambreByIdResponse\0228\n\013SaveChamb" +
      "re\022\023.SaveChambreRequest\032\024.SaveChambreRes" +
      "ponse\022>\n\rdeleteChambre\022\025.DeleteChambreRe" +
      "quest\032\026.DeleteChambreResponse2\276\002\n\022Reserv" +
      "ationService\022J\n\017AllReservations\022\032.GetAll" +
      "ReservationsRequest\032\033.GetAllReservations" +
      "Response\022J\n\017ReservationById\022\032.GetReserva" +
      "tionByIdRequest\032\033.GetReservationByIdResp" +
      "onse\022D\n\017SaveReservation\022\027.SaveReservatio" +
      "nRequest\032\030.SaveReservationResponse\022J\n\021de" +
      "leteReservation\022\031.DeleteReservationReque" +
      "st\032\032.DeleteReservationResponseB\035\n\031com.re" +
      "s.reservation.stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientRequest_descriptor,
        new java.lang.String[] { "Nom", "Prenom", "Email", "Telephone", });
    internal_static_Chambre_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Chambre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Chambre_descriptor,
        new java.lang.String[] { "Id", "Type", "Prix", "Disponible", "Reservations", });
    internal_static_ChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChambreRequest_descriptor,
        new java.lang.String[] { "Type", "Prix", "Disponible", });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "DateDebut", "DateFin", "Preferences", "Client", "Chambre", });
    internal_static_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationRequest_descriptor,
        new java.lang.String[] { "DateDebut", "DateFin", "Preferences", "ClientId", "ChambreId", });
    internal_static_GetAllClientsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetAllClientsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllClientsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllClientsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetAllClientsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllClientsResponse_descriptor,
        new java.lang.String[] { "Clients", });
    internal_static_GetClientByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GetClientByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClientByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetClientByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_GetClientByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetClientByIdResponse_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_SaveClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_SaveClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveClientRequest_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_SaveClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_SaveClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveClientResponse_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_DeleteClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_DeleteClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteClientRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_DeleteClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteClientResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_GetChambreByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_GetChambreByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChambreByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetChambreByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_GetChambreByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChambreByIdResponse_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_SaveChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_SaveChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveChambreRequest_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_SaveChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_SaveChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveChambreResponse_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_DeleteChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_DeleteChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteChambreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_DeleteChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteChambreResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_GetReservationByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_GetReservationByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_GetReservationByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_SaveReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_SaveReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_SaveReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_SaveReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_GetAllReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_GetAllChambresRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_GetAllChambresRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllChambresRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllChambresResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_GetAllChambresResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllChambresResponse_descriptor,
        new java.lang.String[] { "Chambres", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
