// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string dateDebut = 2;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 2;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 3;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 3;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>string preferences = 4;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <code>string preferences = 4;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();

  /**
   * <code>.Client client = 5;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 5;</code>
   * @return The client.
   */
  com.res.reservation.stubs.Client getClient();
  /**
   * <code>.Client client = 5;</code>
   */
  com.res.reservation.stubs.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>.Chambre chambre = 6;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 6;</code>
   * @return The chambre.
   */
  com.res.reservation.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 6;</code>
   */
  com.res.reservation.stubs.ChambreOrBuilder getChambreOrBuilder();
}
