// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface SaveChambreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveChambreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Chambre chambre = 1;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   * @return The chambre.
   */
  com.res.reservation.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   */
  com.res.reservation.stubs.ChambreOrBuilder getChambreOrBuilder();
}
