// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface SaveReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ReservationRequest reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.ReservationRequest reservation = 1;</code>
   * @return The reservation.
   */
  com.res.reservation.stubs.ReservationRequest getReservation();
  /**
   * <code>.ReservationRequest reservation = 1;</code>
   */
  com.res.reservation.stubs.ReservationRequestOrBuilder getReservationOrBuilder();
}
