// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface SaveReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  com.res.reservation.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  com.res.reservation.stubs.ReservationOrBuilder getReservationOrBuilder();
}
