// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package com.res.reservation.stubs;

public interface SaveChambreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveChambreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ChambreRequest chambre = 1;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.ChambreRequest chambre = 1;</code>
   * @return The chambre.
   */
  com.res.reservation.stubs.ChambreRequest getChambre();
  /**
   * <code>.ChambreRequest chambre = 1;</code>
   */
  com.res.reservation.stubs.ChambreRequestOrBuilder getChambreOrBuilder();
}
